main: space.mori.regenblock.RegenBlock
name: RegenBlock
version: @version@
api-version: 1.13

permissions:
    regenblock.self:
        description: Allows to use plugin.
        default: op

commands:
   rb:
      description: Main command
      permission: regenblock.self
      usage: |
          /rb <command>